#
# Configuration file for tracking using sliding
# 
dynamics:
    xLenght: 0.09 #  [meter]
    yLenght: 0.12 #  [meter]
    pusherRadious: 0.01 #  [meter]
    pusherFricCoef: 0.3
    pusherForceLim:  0.3
    pusherAngleVelLim: 2.0
    Kz_max: 50
    Kz_min: 0.1


TO:
    contactMode: 'sticking'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    solverName: 'qpoases'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [1.0, 1.0, 0.01, 0.]  # diagonal state weights
    W_u: [0., 0., 0., 0.]  # diagonal control weights
    K_goal: 10
    X_goal: null
    linDynFlag: False
    codeGenFlag: False
    noPrintingFlag: True
    phases: null
    numObs: 0
